Repository petrolpark/Destroy, pull requests merged in 2024-09, with the labels that each got.

#416 Updated en_gb 'translation'
  src/main/resources/assets/destroy/lang/en_gb.json
Labels: 💬 Translation

#383 Russian translation
  src/main/resources/assets/destroy/lang/ru_ru.json
Labels: 💬 Translation

#374 🍺 Add german translations for chemicals up to fatty_acids
  src/main/resources/assets/destroy/lang/de_de.json
Labels: 💬 Translation

#360 Create ja_jp.json (salt name override)
  ja_jp.json
Labels: 💬 Translation

#339 [PT_BR] Added PT_BR translation
  src/main/resources/assets/destroy/lang/pt_br.json
Labels: 💬 Translation

#342 Fixed the Polish translation and translated some texts
  src/main/resources/assets/destroy/lang/pl_pl.json
Labels: 💬 Translation

#326 Update pl_pl.json 28 Feb 2024
  src/main/resources/assets/destroy/lang/pl_pl.json
Labels: 💬 Translation

#314 🀄️[zh_cn]Simplified Chinese translation repair
  src/main/resources/assets/destroy/lang/zh_cn.json
Labels: 💬 Translation

#359 Create ja_jp.json
  ja_jp.json
Labels: 🤝 Compatibility

#442 Minor Language Additions and GB Tweak
  src/main/resources/assets/destroy/lang/en_gb.json
  src/main/resources/assets/destroy/lang/en_us.json
Labels: 🐛 Bug, 💬 Translation

#465 🍡 Fix gradual temperature increase when vat has liquid
  src/main/java/com/petrolpark/destroy/chemistry/legacy/LegacyMixture.java
Labels: 🐛 Bug
